### ISSUE TITLE
Added to last release

### ISSUE THREAD

**Issue by jeniamoroz** [zattoo/changelog#37]
It would be a good addition to changelog action to validate if added entry goes to last release (even unreleased) block. Fail otherwise.

**Comment by godban** [comment]
Lemme give some examples that should fail:

1. Wrong version was patched

```markdown
## 1.9.1 - 15.01.2077

Hotfix description

### 2.0.0 - 01.01.2077

Release description

### 1.9.0 - 01.01.2025

Release description

...
```

2. Version was added in wrong timeline

```markdown
### 2.0.0 - 01.01.2077

Release description

## 2.1.0 - 15.01.2077

Hotfix description

### 1.9.0 - 01.01.2025

Release description

...
```

3. Unreleased version placed between released versions

```markdown

### 2.0.0 - 01.01.2077

Release description

## Unreleased

Hotfix description

### 1.9.0 - 01.01.2025

Release description

...
```

4. Merge conflict added by mistake same versions

```markdown
### 2.0.0 - 01.01.2077

Release description

### 2.0.0 - 01.01.2077

Release description

### 1.9.0 - 01.01.2025

Release description

...
```

Examples are quite different, so maybe it make sense introduce one by one

**Comment by godban** [comment]
and another one, this time valid one

If pre-release has greater version, it's fine

```markdown
### 2.2.0 - 01.01.2077

Release description

### 3.0.0-rc.0 - 01.01.2055

Release description

### 2.1.0 - 01.01.2025

Release description
```
