### ISSUE TITLE
1.17.0 Error: Cannot read property 'lineNumber' of undefined

### ISSUE THREAD

**Issue by ppolewicz** [zattoo/changelog#65]
no idea why (and there is no instruction on how to debug it, so I can't really investigate it myself). It used to work on the previous version and started crashing recently. Seems like not a lot of people are hitting it, so maybe it's us doing something wrong?

Here's the input file: https://raw.githubusercontent.com/Backblaze/b2-sdk-python/1dd191d126639054472c055ba62fffde9e734ce9/CHANGELOG.md

**Comment by dobladov** [comment]
I found the problem, our regex to validate the heading `## [version] - [year]-[month]-[day]` it's quite strict and it does not support the last "tag" `[YANKED]` in these two lines:

```markdown
33. ## [1.17.1] - 2022-06-23 [YANKED]
38. ## [1.17.0] - 2022-06-23 [YANKED]
```
Here are all the valid options for the heading, https://regex101.com/r/v5VmTx/2

To fix the problem, simply remove `[YANKED]`, or add it like this:

```markdown
33. ## [1.17.1-YANKED] - 2022-06-23
38. ## [1.17.0-YANKED] - 2022-06-23
```
Maybe in the future we can make the regex more robust to indicate the exact problem.
Good idea about having debugging, we could log the parsed changelog and simpay it only when `ACTIONS_RUNNER_DEBUG ` it's present: https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging

**Comment by ppolewicz** [comment]
instead of removing the information about the version being yanked, could we update the regex to tolerate it? Those were bad releases and their name should be spelled correctly - they were yanked because of some build issue that caused the package to not be importable. Yanking the version hides it from `pip` so that it doesn't install it (unless someone really, really wants it to)

**Comment by dobladov** [comment]
Isn't enough to represent it as `1.17.0-YANKED`? Adding the version to the regex will take longer.

**Comment by ppolewicz** [comment]
cool, thanks!
